### PR TITLE
Issue #47 

### PR DESCRIPTION
**Pull request by loganSims**
##### Updated most list views throughout app to recycler views. 
The recycler view is a slimed down more powerful version of the list view. The most noticeable change to the app with this update is the new material look. Using a recycler view allows for fun toolbar interactions with our lists. (things like scrolling toolbars and collapsing toolbars with banners)
Some readings for the recycler view:
* [Android Developer: Creating Lists and Cards](http://developer.android.com/training/material/lists-cards.html)
* [Code Path: Using the Recycler View.](https://github.com/codepath/android_guides/wiki/Using-the-RecyclerView)
* [Blog post about Recycler Views.](https://www.bignerdranch.com/blog/recyclerview-part-1-fundamentals-for-listview-experts/)

The take away is the recycler view offers us more flexibility with our lists.

##### Removed deprecated tab calls in activities with tabs.
We now use the TabLayout class.
Some readings on that:
* [Android Developer: TabLayout](http://developer.android.com/reference/android/support/design/widget/TabLayout.html)
* [Code Path: Google Play Style Tabs Using TabLayout](https://guides.codepath.com/android/google-play-style-tabs-using-tablayout)

##### Use the CursorRecyclerAdapter Class 
As of this update there isn't a standard way to use recycler views with cursors. I pulled in a [class](https://gist.github.com/Shywim/127f207e7248fe48400b) that works like a wrapper for a cursor adapter and recycler view adapter. This way we can use the recycler view will data pulled from our Databases. 

##### Other changes
* Deleted unused social media details activities.
* Gave flickr a fragment and did a little refactoring with it.

### CODE REVIEW

**Comment by waynedyck** [comment]
Fantastic update and documentation! Nice job. I'll pull it down shortly and take a look. It everything looks good we can stage it for a Monday morning deployment.

**Comment by waynedyck** [comment]
Here's what I've observed:

##### All Activities

* The AppBar title text changes in size (gets smaller) when the device is rotated from portrait to landscape.

##### Home Activity / Favorites
* Scrolling through the favorites the header does not collapse.

##### Traffic Map Activity
* The "My Location" button on the map is not showing even though I have location permissions enabled.

##### Camera Activity
* When viewing a video in portrait mode, the video is in the bottom third of the screen. Tapping the video causes the video controls to overlap the bottom Android navigation controls.
* When viewing the video in landscape mode, the bottom part of the video is chopped off.

##### Ferries / Route Schedules / Departure Times
* Scrolling through the departure times the header does not collapse.
* Can the "Day of Week" drop down be moved back into the AppBar with the latest code update?
* Scrolling though the camera images the last one is cut-off. You can't view the bottom of it.
* Viewing the camera images and rotating the device from portrait to landscape or landscape to portrait causes the images to disappear.

##### Ferries / Vessel Watch
* The "My Location" button on the map is not showing even though I have location permissions enabled.

##### Mountain Passes
* When viewing the individual mountain passes and scrolling either the "Report", "Cameras", or "Forecast" the header does not collapse.
* When scrolling to the bottom of the camera images you can see the bottom image. The image is not cut-off as it is when viewing the Ferry terminal cameras.

##### Amtrak Cascades / Check Schedules and Status
* Scrolling through the times the header does not collapse.
* Rotating the device from portrait to landscape while viewing a schedule with no destination selected causes the view to crash. If you have a destination selected it works as expected when rotating the device.

**Comment by loganSims** [comment]
##### All Activities

* ~~The AppBar title text changes in size (gets smaller) when the device is rotated from portrait to landscape.~~ **This is by design, fixed it so the AppBar will shrink accordingly. See [here](http://www.google.com/design/spec/layout/structure.html#structure-app-bar) under "Metrics". If we really don't like it I can look into it further.**

##### Home Activity / Favorites

* Scrolling through the favorites the header does not collapse. **I believe this would require using a  RecyclerAdapter or CursorRecyclerAdapter with the SeperatedListAdapter somehow. Now that I'm more familiar with the recycler view I'll try tackling this one again.**

##### Traffic Map Activity

* The "My Location" button on the map is not showing even though I have location permissions enabled. **It's showing up in my tests. Will continue looking into it**

##### Camera Activity

* ~~When viewing a video in portrait mode, the video is in the bottom third of the screen. Tapping the video causes the video controls to overlap the bottom Android navigation controls.~~

* ~~When viewing the video in landscape mode, the bottom part of the video is chopped off.~~

##### Ferries / Route Schedules / Departure Times

* ~~Scrolling through the departure times the header does not collapse.~~
* Can the "Day of Week" drop down be moved back into the AppBar with the latest code update?
* ~~Scrolling though the camera images the last one is cut-off. You can't view the bottom of it.~~
* Viewing the camera images and rotating the device from portrait to landscape or landscape to portrait causes the images to disappear. **Seems to be in current release version. I'll make an issue for it.**

##### Ferries / Vessel Watch

* The "My Location" button on the map is not showing even though I have location permissions enabled. **It's showing up in my tests. Will continue looking into it**

##### Mountain Passes

* ~~When viewing the individual mountain passes and scrolling either the "Report", "Cameras", or "Forecast" the header does not collapse.~~
* ~~When scrolling to the bottom of the camera images you can see the bottom image. The image is not cut-off as it is when viewing the Ferry terminal cameras.~~

##### Amtrak Cascades / Check Schedules and Status

* ~~Scrolling through the times the header does not collapse.~~

* Rotating the device from portrait to landscape while viewing a schedule with no destination selected causes the view to crash. If you have a destination selected it works as expected when rotating the device. **Seems to be in current release version. I'll make an issue for it.**

**Comment by loganSims** [comment]
Could you explain your comment about the "Day of Week" drop down being moved back into the AppBar? Do you want it in the AppBar similar to how the twitter activity has it?

**Comment by waynedyck** [comment]
Yes, however, I'm not sure if that's possible. Under the old code you could only set one type of navigation mode for the action. It could either be tabs or a drop down list, but not both. For example

`getSupportActionBar().setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);`
or 
`getSupportActionBar().setNavigationMode(ActionBar.NAVIGATION_MODE_LIST);`

Not sure if that is still the case with the new code.

**Comment by loganSims** [comment]
Sounds good. I don't think it'll be a problem. I'd like to think we switch to the toolbar to pull off stuff like that. I'll look into once I'm finished with the new favorites fragment.

**Comment by loganSims** [comment]
Let me know what you think about the toolbar in the favorites. It has a few weird behaviors. The most noticeable being: 
* The collapsing toolbar animation does not activate until the scroll is complete. 
* If you scroll to the bottom of a long favorites list, switch to the home screen, then switch back to favorites, the last item on the list will be cut off because the toolbar is not collapsed and is pushing the last item down.

**Comment by waynedyck** [comment]
I'll see if I can pull this down today and take a look at it.

**Comment by loganSims** [comment]
I just noticed something weird. I added a spinner to the activity_with_tabs.xml file for the Day of the Week drop down in the ferries activity. An empty spinner now shows up in all other activities that use that layout. I will either set spinner visibility to GONE or make separate layout for the ferries activity. Should be an easy fix.

**Comment by waynedyck** [comment]
Awesome job!

**Pull request closed without merging**
