### PR TITLE
Traffic Alerts Update

### PR DESCRIPTION
**Pull request by loganSims**
##### New Feature: Seattle Alerts feature has been removed. Replacing it is "Alerts in This Area" (Name can be changed) #58. 
* When "Alerts in This Area" is selected all alerts being displayed on the map will appear in a list divided into ~~four~~ five categories.
* These categories are Incidents, Construction Closures, Road Closures Special Events and Amber Alerts (when active). 
* Alerts can be touched to open HighwayAlertDetailsActivity for the alert.

##### In the code
* `SeattleIncidentItem.java` has been deleted as it is no longer used. `HighwayAlertItem` is now used in its place. 
* All `SeattleTrafficAlerts*` files have been renamed to simply `TrafficAlerts*`
* `TrafficAlertsFragment.java`  now implements `LoaderCallbacks<Cursor>` instead of `LoaderCallbacks<ArrayList<SeattleIncidentItem>>`. This is because the fragment now gets the information from the highway_alerts table in the database. The class has been refactored to reflect this change.
* `buildCategories()` and the category lists have been removed in favor of constants for the ~~four~~ five category IDs. the IDs are mapped in the new function `getCategoryID(String)` that takes in an alert category and returns the corresponding ID. This function works like `HighwayAlertsOverlay.getCategoryIcon()` but does not take into account alert priority.

### CODE REVIEW

**Comment by waynedyck** [comment]
How will "Special Events" be classified? These usually include baseball, football, soccer events.

**Comment by loganSims** [comment]
They will be classified as "incidents". Now that I'm saying it that does sound strange. 

I'm sorting the events into the categories in the same way we sort them on the map for icons. 

I could change the heading of the incidents section to something like "Incidents and Alerts" or "Accident/Alert" to match http://www.wsdot.com/traffic/trafficalerts/ or I could make a special events ID and change `getCategoryID()` a little.

**Comment by waynedyck** [comment]
I think I'd like to see those in a separate category under "Special Events". Looking at the HighwayAlerts feed now I see a couple that are flagged as "Special Events" and one's a "University of Washington men's basketball game" and the other is a "Seattle Sounders soccer game"

**Comment by waynedyck** [comment]
Merged with commit cfa252996e97a571a4beadfe9756fae7cc80cf4c

**Pull request closed without merging**
